#!/usr/bin/env node

/**
 * SPL-Dev Instance Execution Point - Placeholder Implementation
 * Single execution point at the root of spl-dev install
 */

console.log('Welcome to spl-dev!');

// Get all command line arguments except the first two (node and script path)
const args = process.argv.slice(2);

// Echo the arguments passed to the script
if (args.length > 0) {
    console.log(args.join(' '));
} else {
    console.log('(no arguments provided)');
}